export type { AttachedStorageDTO } from "./AttachedStorageDTO";
export type { VirtualMachineWithCustomConfigDTO } from "./VirtualMachineWithCustomConfigDTO";
export type { VirtualStorageDTO } from "./VirtualStorageDTO";
export type { SnapShotRestoreRequestDTO } from "./SnapShotRestoreRequestDTO";
export type { BackupRestoreRequestDTO } from "./BackupRestoreRequestDTO";
export type { VirtualMachineCreateRequestStoragesInnerDTO } from "./VirtualMachineCreateRequestStoragesInnerDTO";
export type { PortfolioDTO } from "./PortfolioDTO";
export type { SnapShotCreateRequestDTO } from "./SnapShotCreateRequestDTO";
export type { SnapShotDTO } from "./SnapShotDTO";
export type { VirtualMachineWithInstanceTypeDTO } from "./VirtualMachineWithInstanceTypeDTO";
export type { NetworkInterfaceDTO } from "./NetworkInterfaceDTO";
export type { PortfolioArticleDTO } from "./PortfolioArticleDTO";
export type { VirtualMachineCreateRequestDTO } from "./VirtualMachineCreateRequestDTO";
export type { VirtualMachineUpdateRequestDTO } from "./VirtualMachineUpdateRequestDTO";
export type { BackupCreateRequestDTO } from "./BackupCreateRequestDTO";
export type { VirtualMachineDTO } from "./VirtualMachineDTO";
export type { VirtualMachineBaseDTO } from "./VirtualMachineBaseDTO";
export type { BackupDTO } from "./BackupDTO";

export { VirtualMachineStatusEnum } from "./VirtualMachineDTO";
